# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AnimeList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'lottie-ios'
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'RxSwift', '6.6.0'
  pod 'RxCocoa', '6.6.0'
  pod 'RxGesture'
  pod 'SkeletonView'
  pod 'YouTubePlayer'
  pod 'Hero'
  pod 'netfox'
  pod "ToastViewSwift"
  pod 'Parchment', '~> 3.2'
  pod 'FloatingPanel'
  pod 'DGCharts'

  # Pods for AnimeList

end
