# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fuel_management_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ReachabilitySwift'
  pod 'Kingfisher', '~> 7.0'
  pod 'SkeletonView'
  pod 'FloatingPanel'

  # Pods for fuel_management_app

end
